#!/usr/bin/env python3
"""Generate proprietary-files.txt for the RK3576 common tree from a stock dump."""
import hashlib
import os
import re
import sys

# FriendlyELEC NanoPi RK3576, Rockchip SDK ANDROID14_MS_RKR3, built 2026-06-01.
# Dual-arch, and the only dump with the AI-PQ stack. BRINGUP-NOTES.md 7.25.
SRC = "/home/tomin/devel/rk3576/aipq_20260601/out"

# Files that LineageOS builds from source or that the device tree supplies.
EXCLUDE_EXACT = {
    "vendor/build.prop",
    "vendor/build.prop.sorted",  # not part of the ROM; left in the dump by hand
    "vendor/etc/NOTICE.xml.gz",
    "vendor/etc/fs_config_dirs",
    "vendor/etc/fs_config_files",
    "vendor/etc/group",
    "vendor/etc/passwd",
    "vendor/etc/cgroups.json",
    "vendor/etc/task_profiles.json",
    "vendor/etc/vintf/manifest.xml",
    "vendor/etc/vintf/compatibility_matrix.xml",
    # The board tree copies its fstab.rk30board to both the ramdisk and
    # /vendor/etc, so the dump's copy is a duplicate destination that never
    # wins. It is also the one file where taking the Edge-2L version would
    # change policy rather than versions: theirs drops fileencryption= and
    # keydirectory= from the /data line, i.e. no FBE and no metadata
    # encryption, and drops the rkalgo mount this board does have.
    "vendor/etc/fstab.rk30board",
    # Generated by the build system from the VNDK/linker namespace config;
    # shipping the stock copy makes Make override its own build rule.
    "vendor/etc/linker.config.pb",
    # Init scripts a build module already installs to the same path.
    "vendor/etc/init/boringssl_self_test.rc",
    "vendor/etc/init/vndservicemanager.rc",
    "vendor/etc/mkshrc",
    # Dropped, not replaced: declares a service whose binary is in EXCLUDE_BINS.
    "vendor/etc/init/vendor_flash_recovery.rc",
    # LineageOS supplies its own; animation.txt and the images are one set.
    "vendor/etc/res/images/charger/battery_fail.png",
    "vendor/etc/res/images/charger/battery_scale.png",
    "vendor/etc/res/images/charger/font.png",
    "vendor/etc/res/values/charger/animation.txt",
    # Khadas' own framework RRO. It overrides frameworks/base core resources
    # wholesale, which would silently undo the density and config_maxUiWidth
    # work in BRINGUP-NOTES.md 7.15 among much else.
    "vendor/overlay/framework-res__auto_generated_rro_vendor.apk",
    # Already installed by the board tree (27330000_pwm.kl) or by
    # device/lineage/atv. Re-derive with:
    #   comm -12 <(ls device/lineage/atv/keylayout | sort) \
    #            <(ls $SRC/vendor/usr/keylayout | sort)
    "vendor/usr/keylayout/27330000_pwm.kl",
    "vendor/usr/keylayout/Vendor_0002_Product_0002.kl",
    "vendor/usr/keylayout/Vendor_000d_Product_3838.kl",
    "vendor/usr/keylayout/Vendor_000d_Product_3839.kl",
    "vendor/usr/keylayout/Vendor_005d_Product_0001.kl",
    "vendor/usr/keylayout/Vendor_005d_Product_0002.kl",
    "vendor/usr/keylayout/Vendor_0484_Product_5738.kl",
    "vendor/usr/keylayout/Vendor_0508_Product_0110.kl",
    "vendor/usr/keylayout/Vendor_0957_Product_0006.kl",
    "vendor/usr/keylayout/Vendor_0c45_Product_1109.kl",
    "vendor/usr/keylayout/Vendor_1915_Product_0001.kl",
    "vendor/usr/keylayout/Vendor_1d5a_Product_c081.kl",
    "vendor/usr/keylayout/Vendor_1d5a_Product_c082.kl",
    "vendor/usr/keylayout/Vendor_7045_Product_1820.kl",
    "vendor/usr/keylayout/Vendor_7545_Product_0021.kl",
    "vendor/usr/keylayout/Vendor_7545_Product_0180.kl",
    "vendor/usr/keylayout/Vendor_7545_Product_0190.kl",
    # 1.2 MB of recovery patch data for an OTA path this tree does not use.
    "vendor/etc/recovery-resource.dat",
    # The whole usb_modeswitch feature; its configs are excluded below anyway.
    "vendor/bin/usb_modeswitch",
    "vendor/bin/init.usbmod.sh",
    "vendor/lib64/libusb.so",
    # Would outrank the density and config_maxUiWidth set in the overlay.
    "vendor/etc/displayconfig/default.xml",
    # 7.4 MB of sample clips for Rockchip's PQ/codec demo tools.
    "vendor/etc/1080p.h264",
    "vendor/etc/1080p.jpg",
    "vendor/etc/2160p.h264",
    "vendor/etc/480p.jpg",
    "vendor/etc/720p.h264",
    "vendor/etc/720p.jpg",
    # Board data, and the two halves of the same fault: both name the UART the
    # Bluetooth controller is on, and the Edge-2L is /dev/ttyS5 where this board
    # is /dev/ttyS4. bt_vendor.conf tells the HAL which node to open;
    # init.connectivity.rc is what chowns it to the bluetooth user, without
    # which the open fails with EACCES. Supplied by the board tree.
    "vendor/etc/bluetooth/bt_vendor.conf",
    "vendor/etc/init/hw/init.connectivity.rc",
    # Also a board delta, and unrelated to Bluetooth: RKR8 pins policy0 to the
    # performance governor for good. See init-files/init.rk3576.rc.
    "vendor/etc/init/hw/init.rk3576.rc",
    # supplied by device/rockchip/rk35xx-common/configs
    "vendor/etc/a2dp_audio_policy_configuration_7_0.xml",
    "vendor/etc/audio_effects.xml",
    "vendor/etc/audio_policy_configuration.xml",
    "vendor/etc/audio_policy_configuration_singlehal.xml",
    "vendor/etc/audio_policy_volumes_drc.xml",
    "vendor/etc/bluetooth_audio_policy_configuration_7_0.xml",
    "vendor/etc/default_volume_tables.xml",
    "vendor/etc/r_submix_audio_policy_configuration.xml",
    "vendor/etc/usb_audio_policy_configuration.xml",
    "vendor/etc/media_codecs.xml",
    "vendor/etc/media_codecs_c2_base.xml",
    "vendor/etc/media_codecs_google_c2.xml",
    "vendor/etc/media_codecs_performance.xml",
    "vendor/etc/media_profiles_V1_0.xml",
    "vendor/etc/HwComposerEnv.xml",
    "vendor/etc/display_settings.xml",
    "vendor/etc/package_uimode_config.xml",
    # CAS dropped entirely: stock's is AOSP's example service, which now only
    # ships inside the com.android.hardware.cas APEX. Nothing replaces it.
    "vendor/bin/hw/android.hardware.cas-service.example",
    "vendor/etc/init/cas-default.rc",
    "vendor/etc/vintf/manifest/android.hardware.cas-service.xml",
    # ClearKey DRM comes from AOSP source (common.mk) and brings its own .rc and
    # VINTF fragment, so the stock copies would collide.
    "vendor/bin/hw/android.hardware.drm-service.clearkey",
    "vendor/etc/init/android.hardware.drm-service.clearkey.rc",
    "vendor/etc/vintf/manifest/android.hardware.drm-service.clearkey.xml",
    # Declares ISensors/default, but stock ships no implementation of it at all.
    # A declared-but-absent AIDL HAL loops the boot animation: system_server's
    # SensorDevice blocks forever waiting for it. sensors is optional in the
    # framework matrix and the board's accel/gyro do not probe anyway.
    "vendor/etc/vintf/manifest/sensors-rockchip.xml",
    # AOSP's android.hardware.bluetooth.audio-impl is built instead (common.mk)
    # and brings its own bluetooth_audio.xml and libbluetooth_audio_session_aidl,
    # so the stock copies would collide on the same install paths.
    "vendor/etc/vintf/manifest/bluetooth_audio.xml",
}

# --- Soong module name collisions with AOSP ---
# extract_utils names a prebuilt_etc module after its file, and Soong emits an
# install rule for every init_rc and vintf_fragments file in the tree whether or
# not the module is installed. Either way the collision with AOSP is fatal.
# init and VINTF both parse every file in their directory regardless of its
# name, so the fix is to extract to a renamed destination ("src:dst" spec).
RENAME = {
    "vendor/etc/init/android.hardware.audio.service.rc":
        "vendor/etc/init/rk_audio.service.rc",
    "vendor/etc/init/android.hardware.bluetooth@1.0-service.rc":
        "vendor/etc/init/rk_bluetooth@1.0-service.rc",
    "vendor/etc/init/android.hardware.tv.hdmi.cec-service.rc":
        "vendor/etc/init/rk_hdmi.cec-service.rc",
    "vendor/etc/init/android.hardware.tv.hdmi.connection-service.rc":
        "vendor/etc/init/rk_hdmi.connection-service.rc",
    "vendor/etc/init/android.hardware.wifi-service.rc":
        "vendor/etc/init/rk_wifi.service.rc",
    "vendor/etc/vintf/manifest/android.hardware.tv.hdmi.cec-service.xml":
        "vendor/etc/vintf/manifest/rk_hdmi.cec.xml",
    "vendor/etc/vintf/manifest/android.hardware.tv.hdmi.connection-service.xml":
        "vendor/etc/vintf/manifest/rk_hdmi.connection.xml",
    "vendor/etc/vintf/manifest/android.hardware.wifi-service.xml":
        "vendor/etc/vintf/manifest/rk_wifi.service.xml",
    "vendor/etc/vintf/manifest/android.hardware.wifi.hostapd.xml":
        "vendor/etc/vintf/manifest/rk_wifi.hostapd.xml",
    "vendor/etc/vintf/manifest/android.hardware.wifi.supplicant.xml":
        "vendor/etc/vintf/manifest/rk_wifi.supplicant.xml",
    # The only ELF here, and for a different reason: it has to stay the stock
    # Android 14 build (cppbor::Item gained two virtuals, BRINGUP-NOTES.md 7.7)
    # but cannot ship under its own name -- pairing with AOSP's module is
    # refused (theirs is /system) and unpairing collides with the install rule
    # Soong writes for that path anyway. extract-files.py carries the matching
    # fix_soname() and replace_needed()s.
    "vendor/lib64/libcppbor_external.so":
        "vendor/lib64/libcppbor_external_rk.so;FIX_SONAME",
    # SoC-neutral name, selected by ro.hardware.vulkan=mali.
    "vendor/lib/hw/vulkan.rk3576.so": "vendor/lib/hw/vulkan.mali.so",
    "vendor/lib64/hw/vulkan.rk3576.so": "vendor/lib64/hw/vulkan.mali.so",
}

# --- Soong module name collisions with AOSP, the ELF half ---
# A prebuilt whose name matches an AOSP module *replaces* it, which for a vendor
# module of the same kind is exactly what "keep the stock blob" means. Renaming
# is only for where replacement cannot happen, and is only safe when AOSP has no
# install rule for the same path -- libwifi-hal-bcm (AOSP's is a static library,
# and the replacement mutator panics soong_build over the missing variant),
# gpu_counter_producer (AOSP's is /system), hostapd (AOSP's is never installed,
# and unpairing keeps its supplicant-V3 out of our V1 blob's graph). The rest of
# the Wi-Fi HAL family has no AOSP counterpart and carries the suffix for
# consistency. MODULE_SUFFIX keeps the installed file name, which the .rc files
# and runtime dlopen()s use; extract-files.py carries matching lib_fixups.
MODULE_SUFFIX = "-rockchip"
MODULE_SUFFIX_BASENAMES = {
    "gpu_counter_producer",
    "hostapd",
    "libwifi-hal-aic.so",
    "libwifi-hal-bcm.so",
    "libwifi-hal-bes.so",
    "libwifi-hal-rtk.so",
    "libwifi-hal-skw.so",
}

# --- Blobs whose declared dependencies have to be suppressed ---
# Both are AIDL *servers* several versions behind the tree (ISupplicant V2 vs
# V5, IWifi V1 vs V4), and Soong refuses a graph with two versions of one
# aidl_interface. Relinking a server is not an option -- it inherits its vtable
# from Bn*, so a newer library gives it slots it does not implement. Dropping
# the declared deps costs the ELF check and means the libraries only these use
# have to be listed by hand in common.mk.
DISABLE_DEPS = {
    "vendor/bin/hw/android.hardware.wifi-service",
    "vendor/bin/hw/wpa_supplicant",
}

EXCLUDE_PREFIX = (
    "vendor/etc/selinux/",       # built from sepolicy sources
    "vendor/etc/permissions/",   # copied from frameworks/native/data/etc
    "vendor/apex/",              # APEXes are rebuilt
    "vendor/app/",               # RkVideoPlayer, with prebuilt odex/vdex
    "vendor/lost+found",
    "vendor/odm/",               # symlink farm
    # 476 config files with no usb_modeswitch binary in the ROM, three of them
    # with a '#' in the name that breaks the generated PRODUCT_COPY_FILES.
    "vendor/etc/usb_modeswitch.d/",
)

# AOSP-built executables that must not be shadowed by prebuilts. Note that "not
# extracted" does not mean "installed": abc, applypatch, wpa_cli and
# install-recovery.sh are in no product package list and are simply absent.
EXCLUDE_BINS = {
    "vendor/bin/abc", "vendor/bin/applypatch", "vendor/bin/awk",
    "vendor/bin/boringssl_self_test32",
    "vendor/bin/boringssl_self_test64",
    "vendor/bin/dumpsys", "vendor/bin/logwrapper", "vendor/bin/sh",
    "vendor/bin/toolbox", "vendor/bin/toybox_vendor", "vendor/bin/vndservice",
    "vendor/bin/vndservicemanager", "vendor/bin/wpa_cli",
}
# NOTE: wpa_supplicant and hostapd are deliberately NOT excluded. AOSP has no
# Wi-Fi HAL for the AIC8800D80, so Rockchip's whole multiplexing stack is kept.

# Core AOSP / VNDK libraries: always rebuilt from source, never extracted.
AOSP_LIBS = {
    "libc", "libm", "libdl", "liblog", "libz", "libc++", "libc++_shared",
    "libbase", "libcutils", "libutils", "libhardware", "libhidlbase",
    "libhidlmemory", "libbinder", "libbinder_ndk", "libvndksupport",
    "libbacktrace", "libunwindstack", "liblzma", "libjsoncpp", "libtinyxml2",
    "libxml2", "libpcre2", "libselinux", "libcrypto", "libssl", "libsqlite",
    "libexpat", "libfmq", "libsync", "libnl", "libprocessgroup", "libsysutils",
    "libnetutils", "libminijail", "libavservices_minijail", "libcutils_sockets",
    "libadbconnection", "libdl_android", "libziparchive", "libasync_safe",
    "libsystem_properties", "libpackagelistparser", "libprocinfo",
    "libstagefright_foundation", "libstagefright_bufferpool@2.0",
    "libcodec2_vndk", "libcodec2_soft_common", "libsfplugin_ccodec_utils",
    "libion", "libdmabufheap", "libgralloctypes", "libui", "libnativewindow",
    "libnativebase", "libnativehelper", "libhwbinder", "libvintf",
    "libaudioutils", "libaudiofoundation", "libaudioroute", "libtinyalsa",
    "libtinycompress", "libeffectsconfig", "libmedia_helper", "libapexutil",
    "libvendorsupport", "libchrome", "libevent",
}

# Prefixes of AOSP-generated HAL interface libraries, built from source instead.
# common.mk pins the exact frozen AIDL version each blob was compiled against;
# AIDL is ABI-frozen, so the result is equivalent to shipping the stock copy.
AOSP_LIB_PREFIXES = (
    "android.hardware.", "android.hidl.", "android.frameworks.",
    "android.system.", "android.media.", "libclang_rt.", "libcodec2_hidl@",
    "libprotobuf-cpp", "libgrpc",
)

# Libraries that only *look* like AOSP interface libraries. Rockchip names some
# of its own implementations after the HAL they implement, and no amount of
# PRODUCT_PACKAGES will conjure those up -- they have to be extracted.
NOT_AOSP_LIBS = {
    "android.hardware.camera.provider-V1-external-impl-rk.so",
}

# --- Blobs that are unmodified AOSP, built from source instead ---
#
# These are implementations, not interface libraries, so "same code" was checked
# rather than assumed -- by authorship against Rockchip's own Android 14 SDK
# tree, per directory that builds the blob:
#
#   RK=/home/tomin/btrfs-subvolumes/android/edge2-a14
#   git -C $RK/<repo> log --format='%ae %s' -- <module dir> | grep rock-chips.com
#
# Empty output means the LineageOS module is a drop-in. Where it was not empty
# the blob stays: audio@7.1-impl, bluetooth@1.0, tv.hdmi.{cec,connection},
# wifi-service and libwifi-hal. libdrm is the exception -- Rockchip did touch it,
# but nothing in the stock image uses what they added, so it is replaced anyway.
# android.hardware.audio.service is kept for an unrelated reason: building it
# would flip it to 32-bit (compile_multilib prefer32).
#
# Matching PRODUCT_PACKAGES entries are in common.mk. Names here are file names,
# matched under vendor/lib{,64} and its hw/, soundfx/ and mediadrm/
# subdirectories, i.e. both bitnesses at once.
AOSP_SOURCE_LIBS = {
    # Audio: ALSA helpers, the effect factory and its bundled effects, and the
    # legacy libhardware audio modules. audio.primary.default.so is AOSP's stub
    # -- the real HAL is audio.primary.rk30board.so, which stays a blob.
    "libalsautils.so", "libalsautilsv2.so", "libtinyalsav2.so",
    "libeffects.so", "libnbaio_mono.so",
    "audio.primary.default.so", "audio.stub.default.so",
    "audio.r_submix.default.so", "audio.usb.default.so",
    "audio.usbv2.default.so",
    "libaudiopreprocessing.so", "libbundlewrapper.so", "libdownmix.so",
    "libdynproc.so", "libeffectproxy.so", "libhapticgenerator.so",
    "libldnhncr.so", "libreverbwrapper.so", "libvisualizer.so",
    "libvibratorutils.so",
    "android.hardware.audio.effect@7.0-impl.so",
    # Bluetooth audio. Building audio.bluetooth.default.so is what lets
    # android.hardware.bluetooth.audio-V3-ndk go away: the from-source build
    # links V4, like the rest of the BT audio stack we already build.
    "audio.bluetooth.default.so", "libbluetooth_audio_session.so",
    # Codec 2 / bufferpool halves that pair with libcodec2_vndk, which is
    # already built from source.
    "libcodec2_hidl_plugin.so", "libstagefright_aidl_bufferpool2.so",
    "libstagefright_bufferpool@2.0.1.so",
    # Camera: the AOSP HIDL device/provider wrappers that Rockchip's
    # camera.device-*-impl-rk.so and the legacy providers link against.
    "camera.device@1.0-impl.so", "camera.device@3.2-impl.so",
    "camera.device@3.3-impl.so", "camera.device@3.4-impl.so",
    "camera.device@3.4-external-impl.so", "camera.device@3.5-impl.so",
    "camera.device@3.5-external-impl.so", "camera.device@3.6-external-impl.so",
    "android.hardware.camera.provider@2.4-impl.so",
    # Graphics
    "libdrm.so", "gralloc.default.so",
    # Security. NOT libcppbor_external.so: all eleven of its vtables grew by 16
    # bytes since Android 14, and the OP-TEE keymint blobs dispatch through the
    # old slot indices. See BRINGUP-NOTES.md 7.7 and tools/check-vendor-vtables.py.
    # libkeymaster4_1support is new in RKR8, and its only consumer is the new
    # vendor/bin/wait_for_optee; AOSP's module is a drop-in and arrives as a
    # shared_libs of that prebuilt.
    "libkeymaster4support.so", "libkeymaster4_1support.so",
    "libkeystore-engine-wifi-hidl.so",
    # DRM: goes with android.hardware.drm-service.clearkey, which common.mk
    # already builds from source.
    "libdrmclearkeyplugin.so",
    # TV input HIDL wrapper (rockchip.hardware.tv.input is the implementation).
    "android.hardware.tv.input@1.0-impl.so",
    # Plain utility libraries.
    "libmemunreachable.so", "libmediautils_vendor.so", "libbinderdebug.so",
    "libz_stable.so", "local_time.default.so",
}

# AIC8800 firmware, matched to the driver and not to the board. Excluded from
# SRC and pinned from the Edge-2L dump below. BRINGUP-NOTES.md 7.26.
AIC_FW_RE = re.compile(
    r"^vendor/etc/firmware/(fmacfw|fw_patch|fw_adid|lmacfw|aic_)")

EDGE2L = "/home/tomin/devel/AmlogicKitchen/edge-2l/level2"

# --- Blobs pinned from a second dump ---
# Emitted as "path|sha1", hashed from the named dump; extract-utils restores
# pinned files from the vendor tree instead of SRC. See README.md.
# Each entry: (section title, source dump, comment lines, paths-or-regex).
PINNED = [
    (
        "AIC8800 Bluetooth firmware",
        "/home/tomin/devel/AmlogicKitchen/rk3576-m9s/level2",
        [
            "Pinned from the H96 Max M9S stock ROM",
            "rk3576_a001_H96_Max_M9S_BTM_ATV-20250314.1513 (Rockchip SDK",
            "ANDROID14_RKR5); the Edge-2L ROM does not ship them.",
        ],
        [
            "vendor/etc/firmware/fmacfwbt.bin",
            "vendor/etc/firmware/fmacfwbt_8800d80_u02.bin",
            "vendor/etc/firmware/fmacfw_calib_8800dc_hbt_u02.bin",
            "vendor/etc/firmware/fmacfw_patch_8800dc_hbt_u02.bin",
            "vendor/etc/firmware/fmacfw_patch_tbl_8800dc_hbt_u02.bin",
        ],
    ),
    (
        "AIC8800 Wi-Fi/BT firmware",
        EDGE2L,
        [
            "Pinned from the Khadas Edge-2L ROM (ANDROID14_RKR8), which is the",
            "set the aic8800_bsp driver in kernel/rockchip/kernel-modules is",
            "built against. Taking the main dump's newer set panics the kernel",
            "in aicbt_patch_info_unpack(). BRINGUP-NOTES.md 7.26.",
        ],
        AIC_FW_RE,
    ),
]

# --- Excluded libraries, either bitness ---
# Matched on basename under vendor/lib{,64} and its subdirectories.
EXCLUDE_LIB_BASENAMES = {
    # Unloadable: wants libandroidicu.so out of the com.android.i18n APEX.
    "libcam_facedetection.so",
    # Goes with the CAS service dropped above.
    "libclearkeycasplugin.so",
    # AOSP's android.hardware.bluetooth.audio-impl is built instead.
    "libbluetooth_audio_session_aidl.so",
    # RIL: no modem on this board, and no radio HAL in the manifest.
    "libril.so", "librilutils.so", "libreference-ril.so",
    # Built from the .hal vendored in hardware/rockchip/interfaces (same
    # source the blobs were generated from), so the in-tree module provides
    # both the vendor variant -- installed through the impl blob's DT_NEEDED
    # -- and the system variant librockchip_servers links. Shipping the
    # extracted .so collides with the built one (partition mismatch).
    "rockchip.hardware.outputmanager@1.0.so",
}

VENDOR_LIB_RE = re.compile(r"^vendor/lib(64)?/[^/]+$")
ANY_VENDOR_LIB_RE = re.compile(r"^vendor/lib(?:64)?/(?:[^/]+/)*([^/]+)$")
AOSP_SOURCE_LIB_RE = re.compile(
    r"^vendor/lib(64)?/(?:hw/|soundfx/|mediadrm/)?([^/]+)$")


def is_aosp_source_lib(path):
    m = AOSP_SOURCE_LIB_RE.match(path)
    return bool(m) and m.group(2) in AOSP_SOURCE_LIBS


def is_aosp_lib(base):
    if not base.endswith(".so"):
        return False
    if base in NOT_AOSP_LIBS:
        return False
    stem = base[:-3]
    # strip a trailing @version (e.g. libfoo@1.0.so)
    if stem in AOSP_LIBS:
        return True
    if stem.split("@")[0] in AOSP_LIBS:
        return True
    return base.startswith(AOSP_LIB_PREFIXES)


# The one prebuilt APEX kept despite the vendor/apex/ exclusion.
KEEP_EXACT = {
    "vendor/apex/com.google.android.widevine.nonupdatable.apex",
}


def is_excluded(path):
    if path in KEEP_EXACT:
        return False
    if path in EXCLUDE_EXACT or path in EXCLUDE_BINS:
        return True
    if path.startswith(EXCLUDE_PREFIX):
        return True
    if AIC_FW_RE.match(path):
        return True
    m = ANY_VENDOR_LIB_RE.match(path)
    if m and m.group(1) in EXCLUDE_LIB_BASENAMES:
        return True
    if VENDOR_LIB_RE.match(path) and is_aosp_lib(os.path.basename(path)):
        return True
    if is_aosp_source_lib(path):
        return True
    return False


def sha1(path):
    with open(path, "rb") as f:
        return hashlib.sha1(f.read()).hexdigest()


def pinned_sections():
    """Emit the PINNED entries as sections, each file with its source hash."""
    out = []
    for title, src, comment, paths in PINNED:
        if hasattr(paths, "search"):
            paths = sorted(
                rel
                for rel in walk_vendor(src)
                if paths.match(rel)
            )
            if not paths:
                sys.exit("no pinned files matched in %s" % src)
        out.append("")
        out.append("## %s" % title)
        out.extend("## %s" % line for line in comment)
        for f in paths:
            full = os.path.join(src, f)
            if not os.path.isfile(full):
                sys.exit("pinned file missing from %s: %s" % (src, f))
            out.append("%s|%s" % (f, sha1(full)))
    return out


def walk_vendor(src):
    """Every non-symlink path under <src>/vendor, relative to <src>."""
    for root, _dirs, names in os.walk(os.path.join(src, "vendor")):
        for n in names:
            full = os.path.join(root, n)
            if os.path.islink(full):
                continue
            yield os.path.relpath(full, src)


def collect():
    return sorted(f for f in walk_vendor(SRC) if not is_excluded(f))


# --- Section layout ---
# One section per HAL or service, holding its binary, .rc, VINTF fragment and
# libraries, the way device/amlogic/g12-common does it. This list is in *match*
# order, most specific first -- the first pattern that matches a path claims it.
# Sections are printed alphabetically, so match and reading order are
# independent. Patterns are case-insensitive and matched anywhere in the path.
CATCH_ALL = "Rockchip platform"

SECTIONS = [
    # Services and their implementations, most specific first.
    ("Bluetooth", r"bluetooth|libbt-|bt_vendor|rtkbt|skwbt|rtl8761bt|fmacfw\w*bt"),
    # libanr.so (audio noise reduction) and libasc_dec.so (VAD / scene
    # detection) look generic but are audio: audio.primary.rk30board.so is the
    # only thing that names libanr, and libasc_dec exports ASC_Set_VAD_Parameter.
    ("Audio", r"audio|alsa|iec958|soundfx|libanr|libasc_dec"),
    # "(?<!d)isp" so that "display" does not read as ISP, while rkisp, preisp
    # and ispp still do.
    ("Camera", r"camera|rkaiq|aiq|(?<!d)isp|media-ctl|v4l2-ctl|rk1608"),
    ("Widevine", r"^vendor/apex/com\.google\.android\.widevine"),
    ("DRM", r"mediadrm|mediacas|drm-service|widevine|clearkey"),
    ("HDMI CEC", r"hdmi\.cec|hdmi_cec"),
    ("HDMI connection", r"hdmi\.connection|hdmi_connection"),
    ("HDCP", r"hdcp"),
    # The OP-TEE HALs, split per service the way their binaries are; each owns
    # its libRk* client libraries too.
    ("Gatekeeper", r"gatekeeper"),
    # "rkp_factory|_rkp\." rather than a bare "rkp", which also matches rkpq.
    ("KeyMint", r"keymint|keymaster|secureclock|sharedsecret|cppcose|rkp_factory"
                r"|_rkp\.|attestation"),
    ("Weaver", r"weaver"),
    ("OP-TEE", r"optee|tee-supplicant|libteec"),
    ("Composer", r"composer|hwc3|hwcomposer"),
    ("Graphics allocator", r"allocator|graphics\.mapper|gralloc|arm\.graphics"),
    ("Display output manager", r"outputmanager|hw_output|baseparameter|hdr_params"),
    ("GPU", r"mali|/egl/|vulkan|gpu"),
    # Rockchip's fixed-function blocks: 2D blit, image enhancement, JPEG.
    ("Hardware engines (RGA, IEP, JPEG)", r"librga|libiep|hwjpeg"),
    # The rkaipq_* models sit with the RKNN runtime that executes them.
    ("NPU / AI-PQ models", r"rknn"),
    ("Picture quality", r"pq|sculptor|vop_base|rkauth|libvdpp"),
    ("Media codec2 / MPP", r"media[._]c2|codec2|libmpp|rockit|vpu"),
    ("Health", r"health|charger"),
    ("Lights", r"lights"),
    ("Memtrack", r"memtrack"),
    # akmd is the compass daemon; lib_sensor_listener_local is what
    # camera.rk30board links for orientation. No ISensors implementation ships
    # in either dump -- see the sensors-rockchip.xml exclusion above.
    ("Sensors", r"akmd|sensor_listener"),
    ("Power", r"power-aidl|power-service"),
    ("Thermal", r"thermal"),
    ("USB", r"usb|udc"),
    ("Wi-Fi", r"wifi|wpa_|hostapd|supplicant"),
    ("Vendor storage", r"vendor_storage"),
    # Buckets for what is left.
    ("Connectivity firmware", r"^vendor/etc/firmware/"),
    ("Keylayouts", r"^vendor/usr/"),
    ("seccomp", r"^vendor/etc/seccomp_policy/"),
    ("Init-files", r"^vendor/etc/(init/|ueventd\.rc$)|fstab|insmod|set_cpu_affinity"
                   r"|set_performance|tune_io"),
]


def main():
    files = collect()
    assigned = {}
    for name, pattern in SECTIONS:
        pred = re.compile(pattern, re.IGNORECASE).search
        for f in files:
            if f not in assigned and pred(f):
                assigned[f] = name
    out = []
    out.append("## All blobs are from the FriendlyELEC NanoPi RK3576 stock")
    out.append("## firmware, built 2026-06-01, Rockchip SDK ANDROID14_MS_RKR3")
    out.append("## (Android 14, SDK 34, vendor API level 34) -- both bitnesses.")

    def spec(f):
        """Emit "src[:dst][;args]" -- dst rename and Soong module rename."""
        dst = RENAME.get(f)
        line = "%s:%s" % (f, dst) if dst else f
        if os.path.basename(f) in MODULE_SUFFIX_BASENAMES:
            line += ";MODULE_SUFFIX=%s" % MODULE_SUFFIX
        if f in DISABLE_DEPS:
            line += ";DISABLE_DEPS"
        return line

    names = sorted(set(assigned.values()), key=str.lower)
    for name in names + [CATCH_ALL]:
        group = [f for f in files if assigned.get(f, CATCH_ALL) == name]
        if not group:
            continue
        out.append("")
        out.append("## %s" % name)
        out.extend(spec(f) for f in group)
    pinned = pinned_sections()
    out.extend(pinned)
    out.append("")
    sys.stdout.write("\n".join(out))
    sys.stderr.write("total blobs: %d in %d sections, plus %d pinned\n" % (
        len(files), len(names) + 1, sum(1 for l in pinned if "|" in l)))


if __name__ == "__main__":
    main()
